country_collection_values:
  - 'countryAF'
  - 'countryAL'
  - 'countryDZ'
  - 'countryAS'
  - 'countryAD'
  - 'countryAO'
  - 'countryAI'
  - 'countryAQ'
  - 'countryAG'
  - 'countryAR'
  - 'countryAM'
  - 'countryAW'
  - 'countryAU'
  - 'countryAT'
  - 'countryAZ'
  - 'countryBS'
  - 'countryBH'
  - 'countryBD'
  - 'countryBB'
  - 'countryBY'
  - 'countryBE'
  - 'countryBZ'
  - 'countryBJ'
  - 'countryBM'
  - 'countryBT'
  - 'countryBO'
  - 'countryBA'
  - 'countryBW'
  - 'countryBV'
  - 'countryBR'
  - 'countryIO'
  - 'countryBN'
  - 'countryBG'
  - 'countryBF'
  - 'countryBI'
  - 'countryKH'
  - 'countryCM'
  - 'countryCA'
  - 'countryCV'
  - 'countryKY'
  - 'countryCF'
  - 'countryTD'
  - 'countryCL'
  - 'countryCN'
  - 'countryCX'
  - 'countryCC'
  - 'countryCO'
  - 'countryKM'
  - 'countryCG'
  - 'countryCD'
  - 'countryCK'
  - 'countryCR'
  - 'countryCI'
  - 'countryHR'
  - 'countryCU'
  - 'countryCY'
  - 'countryCZ'
  - 'countryDK'
  - 'countryDJ'
  - 'countryDM'
  - 'countryDO'
  - 'countryTP'
  - 'countryEC'
  - 'countryEG'
  - 'countrySV'
  - 'countryGQ'
  - 'countryER'
  - 'countryEE'
  - 'countryET'
  - 'countryEU'
  - 'countryFK'
  - 'countryFO'
  - 'countryFJ'
  - 'countryFI'
  - 'countryFR'
  - 'countryFX'
  - 'countryGF'
  - 'countryPF'
  - 'countryTF'
  - 'countryGA'
  - 'countryGM'
  - 'countryGE'
  - 'countryDE'
  - 'countryGH'
  - 'countryGI'
  - 'countryGR'
  - 'countryGL'
  - 'countryGD'
  - 'countryGP'
  - 'countryGU'
  - 'countryGT'
  - 'countryGN'
  - 'countryGW'
  - 'countryGY'
  - 'countryHT'
  - 'countryHM'
  - 'countryVA'
  - 'countryHN'
  - 'countryHK'
  - 'countryHU'
  - 'countryIS'
  - 'countryIN'
  - 'countryID'
  - 'countryIR'
  - 'countryIQ'
  - 'countryIE'
  - 'countryIL'
  - 'countryIT'
  - 'countryJM'
  - 'countryJP'
  - 'countryJO'
  - 'countryKZ'
  - 'countryKE'
  - 'countryKI'
  - 'countryKP'
  - 'countryKR'
  - 'countryKW'
  - 'countryKG'
  - 'countryLA'
  - 'countryLV'
  - 'countryLB'
  - 'countryLS'
  - 'countryLR'
  - 'countryLY'
  - 'countryLI'
  - 'countryLT'
  - 'countryLU'
  - 'countryMO'
  - 'countryMK'
  - 'countryMG'
  - 'countryMW'
  - 'countryMY'
  - 'countryMV'
  - 'countryML'
  - 'countryMT'
  - 'countryMH'
  - 'countryMQ'
  - 'countryMR'
  - 'countryMU'
  - 'countryYT'
  - 'countryMX'
  - 'countryFM'
  - 'countryMD'
  - 'countryMC'
  - 'countryMN'
  - 'countryMS'
  - 'countryMA'
  - 'countryMZ'
  - 'countryMM'
  - 'countryNA'
  - 'countryNR'
  - 'countryNP'
  - 'countryNL'
  - 'countryAN'
  - 'countryNC'
  - 'countryNZ'
  - 'countryNI'
  - 'countryNE'
  - 'countryNG'
  - 'countryNU'
  - 'countryNF'
  - 'countryMP'
  - 'countryNO'
  - 'countryOM'
  - 'countryPK'
  - 'countryPW'
  - 'countryPS'
  - 'countryPA'
  - 'countryPG'
  - 'countryPY'
  - 'countryPE'
  - 'countryPH'
  - 'countryPN'
  - 'countryPL'
  - 'countryPT'
  - 'countryPR'
  - 'countryQA'
  - 'countryRE'
  - 'countryRO'
  - 'countryRU'
  - 'countryRW'
  - 'countrySH'
  - 'countryKN'
  - 'countryLC'
  - 'countryPM'
  - 'countryVC'
  - 'countryWS'
  - 'countrySM'
  - 'countryST'
  - 'countrySA'
  - 'countrySN'
  - 'countryCS'
  - 'countrySC'
  - 'countrySL'
  - 'countrySG'
  - 'countrySK'
  - 'countrySI'
  - 'countrySB'
  - 'countrySO'
  - 'countryZA'
  - 'countryGS'
  - 'countryES'
  - 'countryLK'
  - 'countrySD'
  - 'countrySR'
  - 'countrySJ'
  - 'countrySZ'
  - 'countrySE'
  - 'countryCH'
  - 'countrySY'
  - 'countryTW'
  - 'countryTJ'
  - 'countryTZ'
  - 'countryTH'
  - 'countryTG'
  - 'countryTK'
  - 'countryTO'
  - 'countryTT'
  - 'countryTN'
  - 'countryTR'
  - 'countryTM'
  - 'countryTC'
  - 'countryTV'
  - 'countryUG'
  - 'countryUA'
  - 'countryAE'
  - 'countryUK'
  - 'countryUS'
  - 'countryUM'
  - 'countryUY'
  - 'countryUZ'
  - 'countryVU'
  - 'countryVE'
  - 'countryVN'
  - 'countryVG'
  - 'countryVI'
  - 'countryWF'
  - 'countryEH'
  - 'countryYE'
  - 'countryYU'
  - 'countryZM'
  - 'countryZW'

supported_interface_languages:
  - 'af'
  - 'sq'
  - 'sm'
  - 'ar'
  - 'az'
  - 'eu'
  - 'be'
  - 'bn'
  - 'bh'
  - 'bs'
  - 'bg'
  - 'ca'
  - 'zh-CN'
  - 'zh-TW'
  - 'hr'
  - 'cs'
  - 'da'
  - 'nl'
  - 'en'
  - 'eo'
  - 'et'
  - 'fo'
  - 'fi'
  - 'fr'
  - 'fy'
  - 'gl'
  - 'ka'
  - 'de'
  - 'el'
  - 'gu'
  - 'iw'
  - 'hi'
  - 'hu'
  - 'is'
  - 'id'
  - 'ia'
  - 'ga'
  - 'it'
  - 'ja'
  - 'jw'
  - 'kn'
  - 'ko'
  - 'la'
  - 'lv'
  - 'lt'
  - 'mk'
  - 'ms'
  - 'ml'
  - 'mt'
  - 'mr'
  - 'ne'
  - 'no'
  - 'nn'
  - 'oc'
  - 'fa'
  - 'pl'
  - 'pt-BR'
  - 'pt-PT'
  - 'pa'
  - 'ro'
  - 'ru'
  - 'gd'
  - 'sr'
  - 'si'
  - 'sk'
  - 'sl'
  - 'es'
  - 'su'
  - 'sw'
  - 'sv'
  - 'tl'
  - 'ta'
  - 'te'
  - 'th'
  - 'ti'
  - 'tr'
  - 'uk'
  - 'ur'
  - 'uz'
  - 'vi'
  - 'cy'
  - 'xh'
  - 'zu'

language_collection_values:
  - 'lang_ar'
  - 'lang_bg'
  - 'lang_ca'
  - 'lang_zh-CN'
  - 'lang_zh-TW'
  - 'lang_hr'
  - 'lang_cs'
  - 'lang_da'
  - 'lang_nl'
  - 'lang_en'
  - 'lang_et'
  - 'lang_fi'
  - 'lang_fr'
  - 'lang_de'
  - 'lang_el'
  - 'lang_iw'
  - 'lang_hu'
  - 'lang_is'
  - 'lang_id'
  - 'lang_it'
  - 'lang_ja'
  - 'lang_ko'
  - 'lang_lv'
  - 'lang_lt'
  - 'lang_no'
  - 'lang_pl'
  - 'lang_pt'
  - 'lang_ro'
  - 'lang_ru'
  - 'lang_sr'
  - 'lang_sk'
  - 'lang_sl'
  - 'lang_es'
  - 'lang_sv'
  - 'lang_tr'